// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk88d7b293xzaBMD4FPaDzTbB-o1vgMBY',
    appId: '1:467777098049:web:e270f7376416366e5291c0',
    messagingSenderId: '467777098049',
    projectId: 'flutter-do-app',
    authDomain: 'flutter-do-app.firebaseapp.com',
    storageBucket: 'flutter-do-app.appspot.com',
    measurementId: 'G-JKBR3F5JHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp4u8StDbWUM1XQgIVsp8VAvU7OTR_kr0',
    appId: '1:467777098049:android:4e55cdc0fd520dab5291c0',
    messagingSenderId: '467777098049',
    projectId: 'flutter-do-app',
    storageBucket: 'flutter-do-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8KiYKOUfrbcMjlRtMxF-aHHTEbPpqKXE',
    appId: '1:467777098049:ios:7882923f2255ca935291c0',
    messagingSenderId: '467777098049',
    projectId: 'flutter-do-app',
    storageBucket: 'flutter-do-app.appspot.com',
    iosBundleId: 'com.example.flutterDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8KiYKOUfrbcMjlRtMxF-aHHTEbPpqKXE',
    appId: '1:467777098049:ios:7882923f2255ca935291c0',
    messagingSenderId: '467777098049',
    projectId: 'flutter-do-app',
    storageBucket: 'flutter-do-app.appspot.com',
    iosBundleId: 'com.example.flutterDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk88d7b293xzaBMD4FPaDzTbB-o1vgMBY',
    appId: '1:467777098049:web:091bd8a6b401b8735291c0',
    messagingSenderId: '467777098049',
    projectId: 'flutter-do-app',
    authDomain: 'flutter-do-app.firebaseapp.com',
    storageBucket: 'flutter-do-app.appspot.com',
    measurementId: 'G-H32V2P1TQV',
  );
}
